// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmoothLlmImposter.Infrastructure.Persistence;

#nullable disable

namespace SmoothLlmImposter.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ImposterDbContext))]
    [ExcludeFromCodeCoverage]
    partial class ImposterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmoothLlmImposter.Domain.Credentials.ProviderCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthScheme")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BaseUrlOverride")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dialect")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SecretCiphertext")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Dialect", "ProviderName", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_ProviderCredentials_Dialect_ProviderName_Name");

                    b.ToTable("ProviderCredentials", (string)null);

                    b.HasDiscriminator<string>("Dialect").HasValue("ProviderCredential");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SmoothLlmImposter.Domain.Credentials.AnthropicCredential", b =>
                {
                    b.HasBaseType("SmoothLlmImposter.Domain.Credentials.ProviderCredential");

                    b.Property<string>("AnthropicVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasDiscriminator().HasValue("anthropic");
                });

            modelBuilder.Entity("SmoothLlmImposter.Domain.Credentials.OpenAiCredential", b =>
                {
                    b.HasBaseType("SmoothLlmImposter.Domain.Credentials.ProviderCredential");

                    b.HasDiscriminator().HasValue("openai");
                });
#pragma warning restore 612, 618
        }
    }
}
